// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	button: {
		/**
		 * A​b​o​u​t
		 */
		about: string
		/**
		 * B​a​c​k
		 */
		back: string
		/**
		 * G​O
		 */
		go: string
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * T​o​g​g​l​e​ ​d​a​r​k​ ​m​o​d​e
		 */
		toggle_dark: string
		/**
		 * C​h​a​n​g​e​ ​l​a​n​g​u​a​g​e​s
		 */
		toggle_langs: string
	}
	intro: {
		/**
		 * O​p​i​n​i​o​n​a​t​e​d​ ​S​v​e​l​t​e​ ​S​t​a​r​t​e​r​ ​T​e​m​p​l​a​t​e
		 */
		desc: string
		/**
		 * D​e​m​o​ ​o​f​ ​d​y​n​a​m​i​c​ ​r​o​u​t​e
		 */
		dynamic_route: string
		/**
		 * H​i​,​ ​{​n​a​m​e​}​!
		 * @param {unknown} name
		 */
		hi: RequiredParams<'name'>
		/**
		 * W​h​a​t​'​s​ ​y​o​u​r​ ​n​a​m​e​?
		 */
		whats_you_name: string
	}
	/**
	 * N​o​t​ ​f​o​u​n​d
	 */
	not_found: string
}

export type TranslationFunctions = {
	button: {
		/**
		 * About
		 */
		about: () => LocalizedString
		/**
		 * Back
		 */
		back: () => LocalizedString
		/**
		 * GO
		 */
		go: () => LocalizedString
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * Toggle dark mode
		 */
		toggle_dark: () => LocalizedString
		/**
		 * Change languages
		 */
		toggle_langs: () => LocalizedString
	}
	intro: {
		/**
		 * Opinionated Svelte Starter Template
		 */
		desc: () => LocalizedString
		/**
		 * Demo of dynamic route
		 */
		dynamic_route: () => LocalizedString
		/**
		 * Hi, {name}!
		 */
		hi: (arg: { name: unknown }) => LocalizedString
		/**
		 * What's your name?
		 */
		whats_you_name: () => LocalizedString
	}
	/**
	 * Not found
	 */
	not_found: () => LocalizedString
}

export type Formatters = {}
